### ISSUE TITLE
Rewrite: TODO list

### ISSUE THREAD

**Issue by DaMatrix** [DaMatrix/Pork2b2tBot#16]
- [ ] GUI interface
- [ ] Interactive console
- [x] WebSocket protocol thingy
- [ ] Multi-client? Probably uneeded...
- [ ] Possibly some kind of plugin system
- [ ] Possibly some kind of proxy-level command system

**Comment by IronException** [comment]
add a way for plugins, please
